config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'sessions'
             }

  devise_scope :user do
    get 'sign_out', to: 'sessions#destroy'
  end

  root 'application#index'
  get 'about', to: 'application#about'
  get 'api_documentation', to: 'application#api'
  get 'about_bip', to: 'application#about_bip'

  resources :submissions do
    member do
      patch :publish
      patch :revoke
    end
    resources :uploads, controller: 'submissions/uploads', only: [:new, :create, :destroy]
  end
  resources :depositions, only: [:new, :create]
  resources :plant_lines, only: [:index]
  resources :plant_varieties, only: [:index]
  resources :plant_parts, only: [:index]
  resources :plant_populations, only: [:index]
  resources :plant_trials, only: [:index, :show]
  resources :trait_descriptors, only: [:index]
  resources :traits, only: [:index]
  resources :trial_scorings, only: [:show]
  resources :data_tables, only: [:index, :show]
  resources :analyses, except: [:edit]

  namespace :analyses do
    resources :data_files, controller: 'data_files', only: [:new, :create, :destroy, :show]
  end

  get 'search', to: 'searches#counts'
  get 'browse_data', to: 'data_tables#index', defaults: { model: 'plant_populations' }

  resource :api_keys, only: [:show] do
    member do
      put :recreate
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get_constraints = {
        plural_model_name: /#{Api.readable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      post_constraints = {
        plural_model_name: /#{Api.writable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      publishable_constraints = {
        plural_model_name: /#{Api.publishable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      get ":plural_model_name", to: 'resources#index', constraints: get_constraints
      get ":plural_model_name/:id", to: 'resources#show', constraints: get_constraints
      post ":plural_model_name", to: 'resources#create', constraints: post_constraints
      delete ":plural_model_name/:id", to: 'resources#destroy', constraints: post_constraints
      patch ":plural_model_name/:id/publish", to: 'resources#publish', constraints: publishable_constraints
      patch ":plural_model_name/:id/revoke", to: 'resources#revoke', constraints: publishable_constraints
    end
  end

  namespace :admin do
    resources :traits, only: [:index, :new, :create, :edit, :update]
  end
end

app/views/submissions/steps/trial/_step01.html.haml
.form-group
  = content.text_field :plant_trial_name, required: true,
    help: 'Please, provide convenient <b>name</b> for this scoring trial. It has to be <b>unique</b>.'

%fieldset
  %legend Traits

  .info-block
    Before uploading your trait score sheet, please choose <b>existing trait descriptors</b>
    that were scored in the course of this trial, or define <b>new trait descriptors.</b>
    Further instructions are found below.
    Examples of plant traits in the database are: 'oleic acid content' or ' seed mature time'.

  .form-group
    = label_tag "Submitted trait scoring data status"
    %br
    = content.label :data_status, "Raw data", value: 'raw_data', class: 'radio-inline' do
      = content.radio_button :data_status, 'raw_data', checked: true
      Raw data
    = content.label :data_status, "Processed data", value: 'processed_data', class: 'radio-inline' do
      = content.radio_button :data_status, 'processed_data'
      Processed data
    %small.help-block
      Please provide information on the nature of your data. Select
      %b Raw data
      if you plan to submit trait scoring values unprocessed in any way. You can also submit technical replicate
      readings, if you have them, by selecting this option. Please select
      %b Processed data
      if you have performed some processing (e.g., mean computation, selected values exclusion) with the
      scoring data prior to the submission. If you would like to upload both types of data set (i.e., raw and processed
      data), please do that using two separate Trial submissions.

  .form-group
    = content.label :trait_descriptor_list
    - options = options_for_submission_select(@content.existing_trait_descriptors, :trait_name)
    - options.concat options_for_submission_select(@content.new_trait_descriptors, :trait, id: false)
    = content.select :trait_descriptor_list, options.html_safe, {},
      { multiple: true,
        class: 'trait-descriptor-list form-control',
        'data-placeholder': "Select trait descriptors" }

  %button.btn.btn-default.new-trait-descriptor-for-list{ type: :button } Add new Trait descriptor

  .panel.panel-info.new-trait-descriptor-for-list.hidden
    .panel-heading
      %h4 Add new <b>Trait descriptor</b>

    .panel-body{"data-dirty-context": "new-trait-descriptor"}
      .info-block
        <b>Important:</b> If the trait you look for is missing you need to contact us
        by #{support_email_link("email", "[BIP] New trait request")} and it will be added to our database.

      .form-group
        = label_tag :trait, nil, class: 'required'
        = select_tag :trait, [], class: 'trait form-control required', 'data-placeholder': 'Select a value'
        %small.help-block Select the trait definition.

      .form-group
        - values = TraitDescriptor.visible(current_user.id).attribute_values('units_of_measurements')
        - option_tags = options_for_select(values)
        = combo_field_tag :units_of_measurements, nil, option_tags, class: 'units-of-measurements', required: true,
            label: t('submission.steps.trial.step01.new_trait_descriptor_attributes.units_of_measurements')
        %small.help-block
          = t 'submission.steps.trial.step01.new_trait_descriptor_attribute_hints.units_of_measurements'

      .form-group
        = label_tag :scoring_method, nil, class: 'required'
        = text_area_tag :scoring_method, nil, class: 'form-control required'
        %small.help-block Describe in detail how the measurement is to be performed.

      .form-group
        = label_tag :materials
        = text_area_tag :materials, nil, class: 'form-control'
        %small.help-block Materials required for scoring.

      .form-group
        = label_tag :plant_part_id, nil
        = select_tag :plant_part_id, [], class: 'plant-part-id form-control', 'data-placeholder': 'Select a plant part'
        %small.help-block Select the part of plant one should use for scoring this trait.

      = render partial: "submissions/annotations", locals: { model: TraitDescriptor }

      .action-buttons
        %button.btn.btn-default.cancel-new-trait-descriptor-for-list{type: 'button'} Cancel
        %button.btn.btn-primary.add-new-trait-descriptor-for-list{type: 'button'} Confirm

  - @content.new_trait_descriptors.each do |trait_descriptor|
    %div{id: "new-trait-descriptor-#{trait_descriptor.trait.split.join('-').downcase}"}
      - @content.class.new_trait_descriptor_properties.each do |attr|
        = hidden_field_tag "submission[content][new_trait_descriptors][][#{attr}]", trait_descriptor.send(attr)

app/views/submissions/steps/trial/_step02.html.haml
.info-block
  %p
    The BIP service assumes that each row in the trait scoring sheet, that you are going to submit,
    represents a so-called <b>plant scoring unit</b>. For raw data it may simply be an individual
    plant in your experiment. For processed data a plant scoring unit may represent a set of plants,
    related to each other in some way. It is mandatory to provide plant accession information
    for each plant scoring unit in the scoring sheet to be submitted.

  %p
    In case you would like to check what plant accessions are currently registered in the BIP, please use the
    = link_to 'plant accessions table view', data_tables_path(model: 'plant_accessions'), target: '_blank'
    (you may filter data in that table with the <b>Search</b> text field).

  %p
    If you submit raw data, you will have an option to submit technical replicate readings as
    well as design factors (for instance, ordinal numbers for plots, reps and so forth).

.fieldset
  %legend Origin of genetic material used in this trial
  .form-group
    = content.label :lines_or_varieties, "Plant lines", value: 'plant_lines', class: 'radio-inline' do
      = content.radio_button :lines_or_varieties, 'plant_lines', checked: true
      Plant lines
    = content.label :lines_or_varieties, "Plant varieties", value: 'plant_varieties', class: 'radio-inline' do
      = content.radio_button :lines_or_varieties, 'plant_varieties'
      Plant varieties
    %small.help-block
      Per each plant scoring unit submitted, the source of genetic material should be provided.
      It may either be a <b>plant line</b> or a <b>plant variety (cultivar)</b>.
      This choice depends on the type of experiment you are conducting. You should select
      the <b>Plant lines</b> option if you
      %ul
        %li created new genetic material (using, for instance, crossing or mutagenesis) in the course of your project,
        %li or you use former plant line genetic material which is not (yet) recognized as a variety or a cultivar.
      In other cases you should probably select the the <b>Plant varieties</b> option.

- if submission.raw_data?
  %fieldset
    %legend Design factors
    .info-block
      %p
        Please select the appropriate statistical design factors suitable for your experimental setup from
        the drop-down fields. Start by selecting the <b>highest design factor first</b>
        and proceed with the next ones in <b>decreasing</b> size.

      %p
        If your factors are not present in the list provided, please add them manually. While creating new
        factors, please make sure you comply with the rule to submit them in decreasing size, so with the
        highest missing factor (e.g. treatment) first, to lowest missing factor (e.g. plot).
        You are able to mix both predefined factors, from the drop-down list, and your own factor names.

    - values = @content.design_factor_names
    - (0...10).each do |idx|
      .form-group{ class: (:hidden if idx > 0 && values[idx - 1].blank?) }
        - options = options_for_select(DesignFactor::COMMON_NAMES, values[idx])
        = content.combo_field "design_factor_names[]", options, value: values[idx],
            label: "Design factor #{idx + 1}", idx: idx

  %fieldset
    %legend Technical replicate numbers
    .info-block
      %p
        If you are using <i>technical replicates</i> in your experiment, please
        set the number of replicates you are scoring per trait. Leaving the value
        at <b>1</b> means you are not using technical replicates for a given trait.

      - if submission.sorted_trait_names.size > 1
        %p
          You can have varying number of technical replicates for different traits.

    - sorted_trait_names = submission.sorted_trait_names
    - col_count = [4, sorted_trait_names.size].min
    - col_size = 12 / col_count

    - sorted_trait_names.each_slice(col_count).with_index do |trait_names, row_idx|
      .form-group
        .row
          - trait_names.each do |trait_name|
            %div{ class: "col-md-#{col_size}" }= content.label :technical_replicate_numbers, trait_name

        .row
          - trait_names.each.with_index do |trait_name, col_idx|
            - idx = row_idx * col_count + col_idx

            %div{ class: "col-md-#{col_size}", data: { idx: idx } }
              = content.text_field :technical_replicate_numbers,
                  value: @content.technical_replicate_numbers[idx] || 1,
                  label: false, name: "submission[content][technical_replicate_numbers][]"

app/views/submissions/steps/trial/_step03.html.haml
- pl_pv_name = 'line'
- pl_pv_name = 'variety' if submission.content.lines_or_varieties == 'plant_varieties'
- design_factor_names = submission.content.design_factor_names || []
- technical_replicate_numbers = submission.content.technical_replicate_numbers || {}
- rep_traits = technical_replicate_numbers.select{ |k,v| v.to_i > 1 }.to_a

.panel-group#templates
  .panel.panel-info
    .panel-heading
      %h4.panel-title
        %a{ role: :button, data: { toggle: :collapse, parent: "#templates" }, href: "#scoring-template" }
          Scoring template

    .panel-collapse.collapse#scoring-template
      .panel-body
        .row
          .col-md-9
            %p
              Please use the button next to this text to download a trait scoring sheet template in XLS format. The template has been created
              according to the choices you have made so far in this submission. If you see that the headers don’t correspond
              to the data you want to submit, navigate back to previous submission steps and amend them accordingly.
              An altered template can then be downloaded at this step.

          .col-md-3.text-right
            = submission_template_link(new_submission_upload_path(submission))

        %h5 Trait scoring sheet structure
        %p
          The next step requires you to upload a file with scoring values. The required format is simple and features
          %b unique plant scoring unit identification column
          (please go back to step 2 for a short definition of a plant scoring unit), followed by
          - if design_factor_names.present?
            %b #{design_factor_names.size} column(s) for design factors
            selected in the previous step and
          %b 3 column(s) for plant accession information
          (accession id, accession assigning organisation and year it was produced - see below),
          %b another column with plant #{pl_pv_name} name
          (also explained below) and
          %b trait scores
          (including potential technical replicate scores) in further columns.
          The number of columns depends on

        %ul
          %li how many <b>traits</b> you selected in the second step of this submission,
          %li how many <b>design factors</b> you defined in the third step (raw data only),
          %li how many <b>technical replicates</b> you plan to submit (raw data only).

        %p
          Sticking to this template should guarantee correct parsing of score values when you upload the file. Please,
          paste your data, in columns, below the header (thus replacing the placeholder <code>... - replace it</code>
          values).

        - column_letters = ("A".."Z").to_a

        %h5 Plant accession information
        %p
          Accession-related fields (<b>Plant accession</b> identifier -
          in column <b>#{column_letters[design_factor_names.size + 2]}</b>, the <b>Originating organisation</b>
          which issued this accession number - in column <b>#{column_letters[design_factor_names.size + 3]}</b>,
          and the <b>Year produced</b> - in column <b>#{column_letters[design_factor_names.size + 4]}</b> are mandatory.
          If you do not have an Accession defined for your plants, please create one yourself (for example,
          using <code>#{'<institute_name>_<seedbag_id>'}</code>).
          It will serve as a placeholder identifier for the unique genetic material used in your trials.
          Accordingly, it is important that you are able to relate back to the identifier when cross-linking
          with the corresponding genetic data.

        %h5 Plant #{pl_pv_name} column
        %p
          This column is especially important if you <b>submit new accessions</b> (i.e. ones which are not present
          in BIP). Every such new accession will be recorded in BIP and it will be related to a <b>plant #{pl_pv_name}</b>.

          - if pl_pv_name == 'line'
            If there are new plant lines created in the course of your experiment, or if you are using existing
            plant lines which are not present in BIP at the moment, we request that you submit these
            new plant lines first, using the
            = succeed '.' do
              = link_to 'Plant population submission procedure', new_submission_path, target: '_blank'
            Afterwards you will be able to return to this step and proceed with trial data submission
            (to save your draft submission, click the <b>Save & edit later</b> button).

          - else
            If you are using plant varieties (cultivars) which are not listed in BIP, please provide their names
            in column <b>#{column_letters[design_factor_names.size + 4]}</b>. These names will then be recorded in BIP as new
            plant varieties related to your plant accession.

        %p
          - if pl_pv_name == 'line'
            For the list of plant lines currently registered in BIP, you may
            = succeed '.' do
              = link_to 'consult this data table', data_tables_path(model: 'plant_lines'), target: '_blank'
            Please use the values from the <b>Line name</b> column when referring to existing plant lines
            in your XLS file in order to avoid duplications due to differences in spelling..

          - else
            If you are using plant varieties (cultivars) known to BIP, you may
            = link_to 'consult this data table', data_tables_path(model: 'plant_varieties'), target: '_blank'
            in order to find their names.
            Please use the values from the <b>Variety</b> column when referring to existing plant varieties
            in your XLS file in order to avoid duplications due to differences in spelling.

        %h5 Trait scores ordering #{'and technical replicates' if rep_traits.present?}
        %p
          The first line will be treated as a header. Specific values in columns
          <b>#{column_letters[design_factor_names.size + 6]}</b> and further will be treated as scoring for the
          trait whose name matches the corresponding column header. If no match is found, the score will
          be stored by column index. That is, an unmatched column <b>#{column_letters[design_factor_names.size + 7]}</b>
          header will cause all column <b>#{column_letters[design_factor_names.size + 7]}</b>
          values to be treated as scores for the second trait (in the order of input)
          - if rep_traits.present?
            , or the second technical replicate of the first trait,
          defined during the first step of this submission.
          Please <b>be careful when pasting your trait scores beneath the correct headers</b>
          as they may not appear in the order they are recorded in your source spreadsheet.

        - if rep_traits.present?
          %p
            Scoring for technical replicates should be submitted in trait-rep order. For instance, for
            #{rep_traits[0][1]} technical replicates of #{rep_traits[0][0]} scores, the column with values
            measured for the second technical replicate should directly follow the column with scores for
            the first technical replicate (no other trait scores in between).

        %p
          In order to avoid any ordering related issues, <b>please use the XLS template</b>
          provided to you above - this template's header has all trait name
          - if rep_traits.present?
            and technical replicate
          columns in the proper order.

  .panel.panel-info
    .panel-heading
      %h4.panel-title
        %a{ role: :button, data: { toggle: :collapse, parent: "#templates" }, href: "#environment-template" }
          Environment template

    .panel-collapse.collapse#environment-template
      .panel-body
        .row
          .col-md-9
            %p Please use the button next to this text to download a template in XLS format.

          .col-md-3.text-right
            = submission_template_link('/manuals/plant_trial_environment.xls')

        %h5 Template structure
        %p
          The template includes several environment properties as defined by
          the #{link_to "MIAPPE", "http://www.miappe.org/", target: "_blank"} standard.
          Most of these properties can be described by providing single numerical value and corresponding
          unit.

        %p
          There are some exceptions (<i>Type of lamps used</i>, <i>Container type</i>, <i>Rooting medium</i>)
          which do not follow this rule and require choice of an item from drop-down list (orange field) with
          optional description (yellow field). Entering new value instead of using drop-down list is also acceptable.
          More than one value can be provided by using subsequent columns.

        %p
          Finally, <i>pH</i> is another exception as it requires to provide pH value (orange field) at
          corresponding depth range (yellow field). Subsequent columns can be used to describe pH at
          different depths.

  .panel.panel-info
    .panel-heading
      %h4.panel-title
        %a{ role: :button, data: { toggle: :collapse, parent: "#templates" }, href: "#treatment-template" }
          Treatment template

    .panel-collapse.collapse#treatment-template
      .panel-body
        .row
          .col-md-9
            %p Please use the button next to this text to download a template in XLS format.

          .col-md-3.text-right
            = submission_template_link('/manuals/plant_trial_treatment.xls')

        %h5 Template structure
        %p
          The template lists several treatment categories as defined by
          the #{link_to "MIAPPE", "http://www.miappe.org/", target: "_blank"} standard.
          For each category you can describe what treatments were applied by providing:

        %ul
          %li name of the treatment (orange field)
          %li detailed description (yellow field, optional).

        There is no limit for the number of treatments you can include for each category. If possible, please select
        treatment name from the provided drop-down list. However, if required term cannot be found you can enter
        any name and it will be added to the database.

app/views/submissions/steps/trial/_step04.html.haml
.uploaded-trait-scores{ class: "#{'hidden' unless @content.upload}" }
  %pre.parser-logs.alert.alert-warning.hidden
  %pre.parser-errors.alert.alert-danger.hidden

  %pre.parser-summary.alert.alert-success{ class: "#{'hidden' unless @content.upload}" }
    - if @content.upload
      :preserve
        #{@content.upload.parser_summary.join("\n")}

  %pre.parser-warnings.alert.alert-danger{ class: "#{'hidden' unless @content.upload && @content.upload.parser_warnings.present?}" }
    - if @content.upload && @content.upload.parser_warnings.present?
      :preserve
        #{@content.upload.parser_warnings.join("\n")}

  .form-group
    = label_tag :upload, 'Uploaded file'
    %div
      %span.file-name= @content.upload.try(:file_file_name)
      = delete_submission_upload_button(@content.upload,
        class: 'btn btn-default delete-trait-scores-upload')

  .info-block.parser-note
    %p
      Please review the above parsing logs. If there were any critical errors during the process,
      the red section will try to give some hints regarding their nature. You may then try to fix
      the file accordingly, delete the current upload and re-upload the fixed file.

    %p
      Otherwise, if you think the parsing went properly, use the <b>NEXT</b> button to confirm
      these changes and proceed with further steps of submission.

= content.hidden_field :upload_id

app/views/submissions/steps/trial/_step04_before.html.haml
.errors.hidden

= form_tag submission_uploads_path(submission), multipart: true, method: :post do
  = hidden_field_tag "submission_upload[upload_type]", "trait_scores"

  .form-group.fileinput{ class: "#{'hidden' if @content.upload}" }
    .btn.btn-primary.fileinput-button
      %span Choose a file...
      = file_field_tag "submission_upload[file]", class: 'trait-scores-upload'
    %small.help-block
      When you are done preparing your trait scoring data sheet, according to the manual presented above,
      please upload the ready CSV file here.

app/views/submissions/steps/trial/_step05.html.haml
.uploaded-plant-trial-environment{ class: "#{'hidden' unless @content.environment_upload}" }
  %pre.parser-logs.alert.alert-warning.hidden
  %pre.parser-errors.alert.alert-danger.hidden

  %pre.parser-summary.alert.alert-success{ class: "#{'hidden' unless @content.environment_upload}" }
    - if @content.environment_upload
      :preserve
        #{@content.environment_upload.parser_summary.join("\n")}

  .form-group
    = label_tag :environment_upload, 'Uploaded Environment data file'
    %div
      %span.file-name= @content.environment_upload.try(:file_file_name)
      = delete_submission_upload_button(@content.environment_upload,
        class: 'btn btn-default delete-plant-trial-environment-upload')

  .info-block.parser-note
    %p
      Please review the above results. If there were any critical errors during the process,
      the red section will try to give some hints regarding their nature. You may then try to fix
      the file accordingly, delete the current upload and re-upload the fixed file.

    %p
      Otherwise, if you think the parsing went properly, use the <b>NEXT</b> button to confirm
      these changes and proceed with further steps of submission.

= content.hidden_field :environment_upload_id

app/views/submissions/steps/trial/_step05_before.html.haml
.errors.hidden

= form_tag submission_uploads_path(submission), multipart: true, method: :post do
  = hidden_field_tag "submission_upload[upload_type]", "plant_trial_environment"

  .form-group.fileinput{ class: "#{'hidden' if @content.environment_upload}" }
    .btn.btn-primary.fileinput-button
      %span Choose a file...
      = file_field_tag "submission_upload[file]", class: 'plant-trial-environment-upload',
        accept: "application/vnd.ms-excel"

    %small.help-block
      Please upload the XLS file containing Environment data here.

app/views/submissions/steps/trial/_step06.html.haml
.uploaded-plant-trial-treatment{ class: "#{'hidden' unless @content.treatment_upload}" }
  %pre.parser-logs.alert.alert-warning.hidden
  %pre.parser-errors.alert.alert-danger.hidden

  %pre.parser-summary.alert.alert-success{ class: "#{'hidden' unless @content.treatment_upload}" }
    - if @content.treatment_upload
      :preserve
        #{@content.treatment_upload.parser_summary.join("\n")}

  .form-group
    = label_tag :treatment_upload, 'Uploaded Treatment data file'
    %div
      %span.file-name= @content.treatment_upload.try(:file_file_name)
      = delete_submission_upload_button(@content.treatment_upload,
        class: 'btn btn-default delete-plant-trial-treatment-upload')

  .info-block.parser-note
    %p
      Please review the above results. If there were any critical errors during the process,
      the red section will try to give some hints regarding their nature. You may then try to fix
      the file accordingly, delete the current upload and re-upload the fixed file.

    %p
      Otherwise, if you think the parsing went properly, use the <b>NEXT</b> button to confirm
      these changes and proceed with further steps of submission.

= content.hidden_field :treatment_upload_id

app/views/submissions/steps/trial/_step06_before.html.haml
.errors.hidden

= form_tag submission_uploads_path(submission), multipart: true, method: :post do
  = hidden_field_tag "submission_upload[upload_type]", "plant_trial_treatment"

  .form-group.fileinput{ class: "#{'hidden' if @content.treatment_upload}" }
    .btn.btn-primary.fileinput-button
      %span Choose a file...
      = file_field_tag "submission_upload[file]", class: 'plant-trial-treatment-upload',
        accept: "application/vnd.ms-excel"

    %small.help-block
      Please upload the XLS file containing Treatment data here.

app/views/submissions/steps/trial/_step07.html.haml
.uploaded-layout{ class: "#{'hidden' unless @content.layout_upload}" }
  .form-group
    = label_tag :layout, 'Trial layout'

    = link_to(@content.layout_upload.try(:file_url), target: "_blank") do
      %img.layout-image{ src: @content.layout_upload.try(:file_url, :small) }

    %div.alert.alert-warning
      %p
        Uploaded file name:
        = succeed '.' do
          %strong
            %span.file-name= @content.layout_upload.try(:file_file_name)
      %p
        Please click the thumbnail above to see the full size version. In order to save the image in BIP,
        you need to click either
        %strong Save & edit later
        or
        %strong Send
        button. Use the
        %strong Delete
        button right below to replace the image with another one.
      %p
        = delete_submission_upload_button(@content.layout_upload,
          class: 'btn btn-default delete-layout-upload')

= content.hidden_field :layout_upload_id

app/views/submissions/steps/trial/_step07_before.html.haml
.info-block
  If available, please upload an image of the layout of your trial (see
  #{link_to "example", "/images/plant-trial-layout-example.jpg", target: "_blank"}
  published by the
  #{link_to "OREGIN", "http://oregin.info/", target: "_blank"}
  Diversity Trial project).

.errors.hidden

= form_tag submission_uploads_path(submission), multipart: true, method: :post do

  = hidden_field_tag "submission_upload[upload_type]", "plant_trial_layout"

  .form-group.fileinput{ class: "#{'hidden' if @content.layout_upload}" }
    .btn.btn-primary.fileinput-button
      %span Choose a file...
      = file_field_tag "submission_upload[file]", class: 'layout-upload',
        accept: "image/jpeg, image/png, image/gif"

    %small.help-block Accepted file formats are *.png, *.jpg and *.gif.