config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'sessions'
             }

  devise_scope :user do
    get 'sign_out', to: 'sessions#destroy'
  end

  root 'application#index'
  get 'about', to: 'application#about'
  get 'api_documentation', to: 'application#api'
  get 'about_bip', to: 'application#about_bip'

  resources :submissions do
    member do
      patch :publish
      patch :revoke
    end
    resources :uploads, controller: 'submissions/uploads', only: [:new, :create, :destroy]
  end
  resources :depositions, only: [:new, :create]
  resources :plant_lines, only: [:index]
  resources :plant_varieties, only: [:index]
  resources :plant_parts, only: [:index]
  resources :plant_populations, only: [:index]
  resources :plant_trials, only: [:index, :show]
  resources :trait_descriptors, only: [:index]
  resources :traits, only: [:index]
  resources :trial_scorings, only: [:show]
  resources :data_tables, only: [:index, :show]
  resources :analyses, except: [:edit]

  namespace :analyses do
    resources :data_files, controller: 'data_files', only: [:new, :create, :destroy, :show]
  end

  get 'search', to: 'searches#counts'
  get 'browse_data', to: 'data_tables#index', defaults: { model: 'plant_populations' }

  resource :api_keys, only: [:show] do
    member do
      put :recreate
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get_constraints = {
        plural_model_name: /#{Api.readable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      post_constraints = {
        plural_model_name: /#{Api.writable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      publishable_constraints = {
        plural_model_name: /#{Api.publishable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      get ":plural_model_name", to: 'resources#index', constraints: get_constraints
      get ":plural_model_name/:id", to: 'resources#show', constraints: get_constraints
      post ":plural_model_name", to: 'resources#create', constraints: post_constraints
      delete ":plural_model_name/:id", to: 'resources#destroy', constraints: post_constraints
      patch ":plural_model_name/:id/publish", to: 'resources#publish', constraints: publishable_constraints
      patch ":plural_model_name/:id/revoke", to: 'resources#revoke', constraints: publishable_constraints
    end
  end

  namespace :admin do
    resources :traits, only: [:index, :new, :create, :edit, :update]
  end
end

app/models/api_key.rb
class ApiKey < ApplicationRecord

  belongs_to :user

  validates :user, presence: true
  validates :token, presence: true, uniqueness: true

  before_validation :assign_token, on: :create

  def self.normalize_token(token)
    token.to_s.slice(0, 64)
  end

  private

  def assign_token
    while token.blank? || self.class.exists?(token: token)
      self.token = SecureRandom.hex(32)
    end
  end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :authenticate_user!

  def show
    @api_key = current_user.api_key

    respond_to do |format|
      format.json { render json: { api_key: @api_key.try(:token) } }
      format.html
    end
  end

  def recreate
    current_user.api_key.try(:destroy)
    current_user.create_api_key!

    redirect_to api_keys_url, notice: 'API Key renewed'
  end

end

app/views/api_keys/show.html.haml
.container
  .h2.page-title API Key

  .row
    .col-sm-6
      %p Your can access BIP API using the following key:
      %p
        %code
          = @api_key.token

      %p
        This is your
        %strong personal
        secret key and should not be shared with others. Please, consult
        = link_to t('menu.api'), navbar_menu[:api]
        for more information.

    .col-sm-6
      %p
        In case you would like to revoke the current key for some reason
        (e.g., you think it is compromised), please
        %strong Renew
        it.

      %p
        = button_to(recreate_api_keys_path, method: "put", class: 'btn btn-danger') { "Renew key" }

      %p.text-danger
        %strong Important.
        This operation will revoke your current API Key. That means it will no
        longer be valid and every future API call using that API Key value will fail.
        When you decide to renew your API Key, please make sure that you use
        the new value in your BIP client.