config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'sessions'
             }

  devise_scope :user do
    get 'sign_out', to: 'sessions#destroy'
  end

  root 'application#index'
  get 'about', to: 'application#about'
  get 'api_documentation', to: 'application#api'
  get 'about_bip', to: 'application#about_bip'

  resources :submissions do
    member do
      patch :publish
      patch :revoke
    end
    resources :uploads, controller: 'submissions/uploads', only: [:new, :create, :destroy]
  end
  resources :depositions, only: [:new, :create]
  resources :plant_lines, only: [:index]
  resources :plant_varieties, only: [:index]
  resources :plant_parts, only: [:index]
  resources :plant_populations, only: [:index]
  resources :plant_trials, only: [:index, :show]
  resources :trait_descriptors, only: [:index]
  resources :traits, only: [:index]
  resources :trial_scorings, only: [:show]
  resources :data_tables, only: [:index, :show]
  resources :analyses, except: [:edit]

  namespace :analyses do
    resources :data_files, controller: 'data_files', only: [:new, :create, :destroy, :show]
  end

  get 'search', to: 'searches#counts'
  get 'browse_data', to: 'data_tables#index', defaults: { model: 'plant_populations' }

  resource :api_keys, only: [:show] do
    member do
      put :recreate
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get_constraints = {
        plural_model_name: /#{Api.readable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      post_constraints = {
        plural_model_name: /#{Api.writable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      publishable_constraints = {
        plural_model_name: /#{Api.publishable_models.map { |klass| klass.name.underscore.pluralize }.join("|")}/
      }

      get ":plural_model_name", to: 'resources#index', constraints: get_constraints
      get ":plural_model_name/:id", to: 'resources#show', constraints: get_constraints
      post ":plural_model_name", to: 'resources#create', constraints: post_constraints
      delete ":plural_model_name/:id", to: 'resources#destroy', constraints: post_constraints
      patch ":plural_model_name/:id/publish", to: 'resources#publish', constraints: publishable_constraints
      patch ":plural_model_name/:id/revoke", to: 'resources#revoke', constraints: publishable_constraints
    end
  end

  namespace :admin do
    resources :traits, only: [:index, :new, :create, :edit, :update]
  end
end

app/models/trait.rb
class Trait < ApplicationRecord
  has_many :trait_descriptors

  validates :name, presence: true, uniqueness: true
  validates :label, presence: true

  include Filterable

  def self.names
    order(:name).pluck(:name)
  end

  def self.permitted_params
    [
      search: [
        'name'
      ],
      query: [
        'id'
      ]
    ]
  end
end

app/controllers/admin/traits_controller.rb
class Admin::TraitsController < Admin::BaseController
  def index
    @traits = Trait.all
  end

  def new
    @trait = Trait.new(canonical: false)
  end

  def edit
    @trait = Trait.find(params[:id])
  end

  def create
    @trait = Trait.new(create_params)

    if @trait.save
      redirect_to admin_traits_path, notice: "Trait '#{@trait.name}' created"
    else
      render :new
    end
  end

  def update
    @trait = Trait.find(params[:id])

    if @trait.update(update_params)
      redirect_to admin_traits_path, notice: "Trait '#{@trait.name}' updated"
    else
      render :edit
    end
  end

  private

  def create_params
    params.require(:trait).permit(:name, :label, :description, :canonical, :data_provenance)
  end

  def update_params
    params.require(:trait).permit(:label, :description, :canonical, :data_provenance)
  end
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController
  def index
    page = params[:page] || 1
    traits = Trait.filter(params).order(:name)
    render json: {
      results: traits.page(page),
      page: page,
      per_page: Kaminari.config.default_per_page,
      total_count: traits.count
    }
  end
end

app/views/admin/traits/_form.html.haml
= form_for([:admin, @trait]) do |f|
  = render partial: "/errors", locals: { errors: @trait.errors }

  .form-group
    = f.text_field :name, required: true, disabled: @trait.persisted?,
      help: "Trait's name cannot be changed after its creation."

  .form-group
    = f.text_field :label, required: true, help: "Eg. ontological term or 'BIP/EI' for traits not defined in any ontology."

  .form-group
    = f.text_area :description

  .form-group
    = f.label :canonical

    %br

    = f.label :canonical, value: "true", class: "radio-inline" do
      = f.radio_button :canonical, 'true'
      Yes

    = f.label :canonical, value: "false", class: "radio-inline" do
      = f.radio_button :canonical, 'false'
      No

    %small.help-block Select 'Yes' for traits defined in an ontology. Please supply ontological term as the label in such case.

  .form-group
    = f.text_area :data_provenance

  .form-group.actions
    = link_to "Cancel", admin_traits_path, class: "btn btn-default btn-back"

    .pull-right
      = f.submit class: "btn btn-primary"

app/views/admin/traits/_traits.html.haml
%table.table.table-condensed.table-browse.table-hover.data-table#traits
  %thead
    %tr
      %th= Trait.human_attribute_name(:name)
      %th= Trait.human_attribute_name(:label)
      %th= Trait.human_attribute_name(:description)
      %th= Trait.human_attribute_name(:canonical)
      %th= Trait.human_attribute_name(:data_provenance)
      %th

  - traits.each do |trait|
    %tr
      %td= trait.name
      %td= trait.label
      %td= trait.description
      %td= trait.canonical ? "Yes" : "No"
      %td= trait.data_provenance
      %td.actions
        = link_to "Edit", edit_admin_trait_path(trait), class: "btn btn-default btn-sm"

app/views/admin/traits/edit.html.haml
.container
  %h2.page-title.no-navbar
    Edit trait: #{@trait.name}

  = render partial: "form"

app/views/admin/traits/index.html.haml
.container
  %h2.page-title.no-navbar
    Traits

    .actions= link_to "New trait", new_admin_trait_path, class: "btn btn-primary"

  - if @traits.present?
    = render partial: 'traits', locals: { traits: @traits }

  - else
    .alert.alert-info
      %p No traits defined

app/views/admin/traits/new.html.haml
.container
  %h2.page-title.no-navbar
    New trait

  = render partial: "form"